### ISSUE TITLE
about the MAP calculation

### ISSUE THREAD

**Issue by geyutang** [CrickWu/GCMC#1]
hi,
when reading your paper, I am confused with the MAP(Mean Average Precision) result.  Which equations are used for this calculation? is it supposed to between 0 and 1? 

thank you for your kindly reply.

**Comment by CrickWu** [comment]
Yes, the value for the MAP is between 0 and 1. The stats in the paper is in its percentage, and it basically is the average of precisions from different lists. You could see the link below for the specific details. https://github.com/CrickWu/GCMC/blob/bf8486bea6679e3e287cad344c9f4ae515c41dfb/src/utils/eval.py#L147

**Comment by geyutang** [comment]
thx,  got it!
